version: '3.9'
services:
  db:
    container_name: adr_db
    image: postgres
    restart: always
    env_file: .env
    networks:
      - inter-net
    ports:
      - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'

volumes:
  data:

networks:
  inter-net:
    driver: bridge
